# Generated by Django 5.2.4 on 2025-07-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0002_sitesettings_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_title', models.CharField(default='Palghar, India', max_length=255)),
                ('address_details', models.CharField(default='Rathod Bhavan Bldg., 1st Floor Next to Tembhode Road', max_length=255)),
                ('phone', models.CharField(default='+91 8983672417', max_length=50)),
                ('phone_note', models.CharField(default='Mon to Fri 9am to 6 pm', max_length=100)),
                ('email', models.EmailField(default='jenilgrathod@gmail.com', max_length=254)),
                ('email_note', models.CharField(default='Send us your query anytime!', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
