# Generated by Django 5.2.4 on 2025-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0003_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Introduce about myself', max_length=200)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
