# Generated by Django 5.2.4 on 2025-07-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0004_aboutsection_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='My Portfolio', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(default='default/logo.png', upload_to='logos/'),
        ),
    ]
