# Generated by Django 5.2.4 on 2025-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0009_educationtraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_month', models.CharField(max_length=20)),
                ('start_year', models.IntegerField()),
                ('end_month', models.CharField(max_length=20)),
                ('end_year', models.IntegerField()),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activities', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EducationTraining',
        ),
    ]
