# Generated by Django 5.2.4 on 2025-07-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0010_education_delete_educationtraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education_images/'),
        ),
    ]
