# Generated by Django 5.2.4 on 2025-07-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0011_education_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='no', max_length=255),
            preserve_default=False,
        ),
    ]
